# Generated by Django 5.1.4 on 2025-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.CharField(choices=[('Work', 'Work'), ('Personal', 'Personal'), ('Urgent', 'Urgent'), ('Other', 'Other')], default='Work', max_length=20),
        ),
    ]
