# Generated by Django 5.1.4 on 2025-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='custom_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
